// Code generated by "stringer -type=Face"; DO NOT EDIT.

package cards

import "strconv"

const _Face_name = "TwoThreeFourFiveSixSevenEightNineTenJackQueenKingAce"

var _Face_map = map[Face]string{
	2:    _Face_name[0:3],
	4:    _Face_name[3:8],
	8:    _Face_name[8:12],
	16:   _Face_name[12:16],
	32:   _Face_name[16:19],
	64:   _Face_name[19:24],
	128:  _Face_name[24:29],
	256:  _Face_name[29:33],
	512:  _Face_name[33:36],
	1024: _Face_name[36:40],
	2048: _Face_name[40:45],
	4096: _Face_name[45:49],
	8192: _Face_name[49:52],
}

func (i Face) String() string {
	if str, ok := _Face_map[i]; ok {
		return str
	}
	return "Face(" + strconv.FormatInt(int64(i), 10) + ")"
}
